name = "linktree"
type = "webpack"
account_id = "c2e2b711a427d3b930925ad760d4f488"
workers_dev = true
route = ""
zone_id = ""
target_type = "webpack"
webpack_config = "webpack.config.js"

[dev]
port = 8000
local_protocol = "http"
